# Service for the application
apiVersion: v1
kind: Service
metadata:
  name: gowebapp-service
  labels:
    app: gowebapp-service
spec:
  selector:
    app: gowebapp
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: gowebapp
  type: NodePort